!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 32
  - - buffer_size
    - 20000
  - - ent_coef
    - auto_0.1
  - - env_wrapper
    - - task.wrapper.ProcessFrame64
      - task.wrapper.ImageToPyTorch
      - task.wrapper.MoveConstraint
      - task.wrapper.TimeLimit:
          max_episode_steps: 250
  - - gamma
    - 0.95
  - - gradient_steps
    - 1
  - - learning_rate
    - lin_0.0003
  - - learning_starts
    - 0
  - - n_timesteps
    - 40000
  - - noise_std
    - 0.025
  - - noise_type
    - normal
  - - optimize_memory_usage
    - true
  - - policy
    - CustomResNetPolicy
  - - policy_kwargs
    - n_critics: 2
      net_arch:
      - 128
      - 128
      use_sde: false
  - - target_entropy
    - auto
  - - tau
    - 0.01
  - - train_freq
    - 1
