PandaTouchEnv_color-v0:
  model_class: 'tqc'
  env_wrapper:
    - task.wrapper.ProcessFrame64
    - task.wrapper.MoveConstraint
  n_timesteps: !!float 1e6
  policy: "CnnPolicy"
  policy_kwargs:
    n_critics: 2
    net_arch: [256, 256]
  learning_rate: !!float 7.3e-4
  buffer_size: 200000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.02
  train_freq: [1, "episode"]
  gradient_steps: -1
  # 10 episodes of warm-up
  learning_starts: 1500
  use_sde_at_warmup: True
  use_sde: True
  sde_sample_freq: 64
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  online_sampling: False