PandaGraspEnv-v0:
  policy: "MlpPolicy"
  policy_kwargs:
    features_extractor_class: "ResNetNetwork"
    features_extractor_kwargs:
      features_dim: 64
  env_wrapper:
    - task.wrapper.ProcessDepthFrame64
    - task.wrapper.DepthToPyTorch
  n_envs: 8
  n_steps: 128
  n_epochs: 4
  batch_size: 256
  n_timesteps: 150000
  learning_rate: lin_2.5e-4
  clip_range: lin_0.1
  vf_coef: 0.5
  ent_coef: 0.01

PandaTouchEnv_color-v0:
  policy: "CustomActorCriticPolicy"
  env_wrapper:
    - task.wrapper.ProcessFrame84
    - task.wrapper.GrayToPyTorch
    - task.wrapper.MoveConstraint
    - task.wrapper.TimeLimit:
        max_episode_steps: 500
  n_envs: 8
  n_steps: 500
  n_epochs: 256
  batch_size: 256
  n_timesteps: 50000
  learning_rate: lin_2.5e-4
  clip_range: lin_0.1
  vf_coef: 0.5
  ent_coef: 0.01
  use_sde: True